apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-kube
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.13.0
    helm:
      values: |
        # for monitoring >]
        metrics:
          enabled: true
        serviceMonitor:
          enabled: true
        # for kind
        args:
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
